---
- name: Realizar comparacoes
  hosts: ubuntu
  vars:
    num1: 10
    num2: 5
  tasks:
    - debug:
        msg:
          - "O valor de num1: {{ num1 }}"
          - "O valor de num2: {{ num2 }}"
          - "num1 é diferente de num2? {{ num1 != num2 }}"
          - "num1 é igual a num2? {{ num1 == num2 }}"
          - "num1 é maior que num2? {{ num1 > num2 }}"
          - "num1 é menor que num2? {{ num1 < num2 }}"
          - "num1 é maior ou igual a num2? {{ num1 >= num2 }}"
          - "num1 é menor ou igual a num2? {{ num1 <= num2 }}"
...
