---
- hosts: all
  tasks:
  - name: Ola mundo na familia RedHat
    shell: "echo 'Ola mundo'"
    when: (ansible_os_family == "RedHat")

  - name: Ola mundo na familia Debian
    shell: "echo 'Ola mundo'"
    when: (ansible_os_family == "Debian" or ansible_distribution_version == "22.04")
...
