---
- name: Ansible tags
  hosts: localhost
  tasks:
  - debug:
      msg: "Esta é a primeira tarefa"
    tags: primeira

  - debug:
      msg: "Esta é a segunda tarefa"
    tags: segunda

  - debug:
      msg: "Esta é a terceira tarefa"
    tags: terceira

  - debug:
      msg: "Esta é a quarta tarefa"
    tags: quarta
...
