Vagrant.configure("2") do |config|

  # Nó Controlador
  config.vm.define "controller" do |vm1|

    # Definindo hostname, SO e rede
    vm1.vm.hostname = "controller"
    vm1.vm.box = "ubuntu/focal64"
    vm1.vm.network "private_network", ip: "192.168.56.11"

    # Definindo o provider, nome no VirtualBox e alocando recursos
    vm1.vm.provider "virtualbox" do |v|
      v.name = "controller"
      v.cpus = "1"
      v.memory = "1024"
      v.gui = false
    end

    # Provisionamento do nó controlador
    vm1.vm.provision "shell", inline: <<-'SHELL'
      sudo apt-get update && sudo apt-get install -y vim
      sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      sudo systemctl restart ssh sshd
    SHELL

  end

  # Nó CentOS
  config.vm.define "centos" do |vm2|

    # Definindo hostname, SO e rede
    vm2.vm.hostname = "centos"
    vm2.vm.box = "centos/7"
    vm2.vm.network "private_network", ip: "192.168.56.12"

    # Definindo o provider, nome no VirtualBox e alocação de recursos
    vm2.vm.provider "virtualbox" do |v|
      v.name = "centos"
      v.cpus = "1"
      v.memory = "512"
      v.gui = false
    end

    # Provisionamento do nó CentOS
    vm2.vm.provision "shell", inline: <<-'SHELL'
      sudo yum install -y vim
      sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      sudo systemctl restart sshd
    SHELL
    
  end

  # Nó Ubuntu
  config.vm.define "ubuntu" do |vm3|

    # Definindo hostname, SO e rede
    vm3.vm.hostname = "ubuntu"
    vm3.vm.box = "ubuntu/focal64"
    vm3.vm.network "private_network", ip: "192.168.56.13"

    # Definindo provider, nome no VirtualBox e alocando recursos
    vm3.vm.provider "virtualbox" do |v|
      v.name = "ubuntu"
      v.cpus = "1"
      v.memory = "512"
      v.gui = false
    end

    # Provisionamento do nó Ubuntu
    vm3.vm.provision "shell", inline: <<-'SHELL'
      sudo apt-get update && sudo apt-get install -y vim
      sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      sudo systemctl restart ssh sshd
    SHELL

  end

end
